[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
rustaml = { git = "https://github.com/Vinz2008/rustaml" }
js-sys = "0.3.77"

[profile.release]
opt-level = "s"
